baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "FikaWorks"
theme = "meghna-hugo"
pygmentsCodeFences = true
pygmentsStyle = "algol_nu"

# Menu
[menu]
    [[menu.nav]]
    name = "Services"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Events"
    URL = "events"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

[taxonomies]

# Site params
[params]
# home= "Home"
logo = "images/logo.svg"
# Meta data
description = "Independent collective of cloud native consultants based in the Netherlands"
author = "FikaWorks"

custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    heading = ""
    content= "We're an independent collective of cloud native consultants based in the Netherlands"
    btn = true
    btnText="Blog"
    btnURL="/blog"

    # call to action
    [params.cta]
    enable = true
    title = "Check out our work on github"
    content = ""
    btnURL = "https://github.com/fikaworks"
    btnText = "github"

    # footer
    [params.footer]
        copyright = "FikaWorks"
        copyrightURL = "http://fika.works"

        # social Icons
        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-facebook"
        # url = "#"

        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-twitter"
        # url = "#"

        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-google-outline"
        # url = "#"

        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-youtube"
        # url = "#"

        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-linkedin"
        # url = "#"

        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-dribbble-outline"
        # url = "#"

        # [[params.footer.socialIcon]]
        # icon = "tf-ion-social-pinterest-outline"
        # url = "#"
