baseURL = "https://fika.works"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "FikaWorks"
theme = "fikaworks"
pygmentsUseClasses = false

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

# Menu
[menu]
    [[menu.nav]]
    name = "Services"
    URL = "/#services"
    weight = 3

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "/#contact"
    weight = 8

    [[menu.nav]]
    name = "Members"
    URL = "members"
    weight = 9


[taxonomies]

# Site params
[params]
  logo = "images/logo.svg"
  description = "We are a collective of independent cloud native consultants based across Europe. We guide our clients on their journey into cloud computing."
  author = "FikaWorks"
  hero_logo = "images/logo-fikaworks-black-transparent.png"
  hero_banner = "images/bump-cropped.jpg"
  blogdescription = "Welcome to our blog where we share our thoughts on technology, the cloud and building a cooperative"
  membersdescription = "Meet the growing FikaWorks family"

  # footer
  [params.footer]
    copyright = "FikaWorks"
    copyrightURL = "http://fika.works"
