baseURL = "https://fika.works"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "FikaWorks"
theme = "fikaworks"
pygmentsUseClasses = false
canonifyURLs = true

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

# Menu
[menu]
    [[menu.nav]]
    name = "Services"
    URL = "/#services"
    weight = 3

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "/#contact"
    weight = 8

[taxonomies]

# Site params
[params]
  logo = "images/logo.svg"
  description = "We are a collective of independent cloud native consultants based across Europe. We guide our clients on their journey into cloud computing."
  author = "FikaWorks"
  hero_logo = "images/logo-fikaworks-black-transparent.png"
  hero_banner = "images/bump-cropped.jpg"

  custom_css = ["css/custom.css"]

    # call to action
    [params.cta]
    enable = true
    title = "Check out our work on github"
    content = ""
    btnURL = "https://github.com/fikaworks"
    btnText = "github"

    # footer
    [params.footer]
      copyright = "FikaWorks"
      copyrightURL = "http://fika.works"
