[settings]
experimental = true
lockfile = true

## cannot use locked at this time because netlify also uses mise to install its
## dependencies
# locked = true

[tools]
hugo-extended = "0.157.0"
node = "24.14.0"

[hooks]
postinstall = ['[ -z "$CI" ] && npm install || true']
