[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  npm ci --include=dev && \
  hugo --gc --minify --baseURL "${URL}"
  """

[build.environment]
HUGO_VERSION = "0.155.0"
NODE_VERSION = "24.13.0"
HUGO_ENV = "production"
TZ = "Europe/Amsterdam"
