[build]

command = "npm ci --also=dev && hugo version && hugo"

[context.production.environment]
HUGO_VERSION = "v0.81.0"
NODE_VERSION = "14"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm ci --also=dev && hugo version && hugo -b $DEPLOY_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.81.0"
NODE_VERSION = "14"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"
NODE_VERSION = "14"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
